WelcomeMessage:
  - "&7Welcome to &6server name&7!"
SendWelcomeMessage: false

onFirstJoin:
  teleport: false
  x: 0
  y: 0
  z: 0

onJoin:
  teleport: false
  x: 0
  y: 0
  z: 0

duplicateIpProtection:
  # 0 - No protection
  # 1 - Max is applied to online players
  # 2 - Max is applied to registered players
  protectionLevel: 0
  maxPerIp: 1
  notifyOnDuplicateIp: true

lang: en_us
