name: Authy
version: 2.1a
author: Iru21
main: me.mateusz.Authy
api-version: 1.18
commands:
  authy:
    description: Information and reloading
    usage: /<command> [reload]
    permission: authy.reload
  register:
    description: Registers the player
    usage: /<command> [haslo] [haslo]
    permission: authy.register
    aliases: reg
  login:
    description: Allows the player to log in
    usage: /<command> [haslo]
    permission: authy.login
    aliases: l
  unregister:
    description: Unregisters the player
    usage: /<command>
    permission: authy.unregister
    aliases: unreg
  remember:
    description: Enables automatic login for the next 48h
    usage: /<command>
    permission: authy.remember
  pin:
    description: Enables and sets a pin code
    usage: /<command>
    permission: authy.pin