name: Authy
version: 1.8b
author: Mateusz#1738
main: me.mateusz.Authy
api-version: 1.17
commands:
  authy:
    description: Informacje i reload
    usage: /<command> [reload]
    permission: authy.reload
  register:
    description: Rejestruje gracza
    usage: /<command> [haslo] [haslo]
    permission: authy.register
    aliases: reg
  login:
    description: Zalogowuje gracza
    usage: /<command> [haslo]
    permission: authy.login
    aliases: l
  unregister:
    description: Odrejetrowuje uzytkownika
    usage: /<command>
    permission: authy.unregister
    aliases: unreg
  remember:
    description: Automatycznie zalogowywuje przez nastepne 48h
    usage: /<command>
    permission: authy.remember
  pin:
    description: Wlacza i ustawia pin
    usage: /<command>
    permission: authy.pin